### ISSUE TITLE
can you make this for python

### ISSUE THREAD

**Issue by levimoore1992** [matheusmonte/hackrank#1]
python

**Comment by matheusmonte** [comment]
I can try, but not at this time. Tons of work. If you want to try , I can help you in translate.

**Comment by levimoore1992** [comment]
Sure not a problem. Thank you

On Oct 8, 2018, at 4:15 PM, Matheus Monte <notifications@github.com> wrote:

I can try, but not at this time. Tons of work. If you want to try , I can help you in translate.

**Comment by VikramProject** [comment]
Below is the python code
req = {}
with open("sample.txt","r") as f:
    for line in f:
        log = line.split(" ")
        req[log[0]] = req.get(log[0],0)+1
with open("output.txt","w") as f2:
    for host,r in req.iteritems():
        f2.write(host+" "+str(r)+"\n")

**Comment by matheusmonte** [comment]
@VikramProject if you want, submit a PR with your solution in a file :)

**Comment by matheusmonte** [comment]
@VikramProject solve this in a comment
